### ISSUE TITLE
HTTP Proxy Option

### ISSUE THREAD

**Issue by ohenepee** [tusharmath/Multi-threaded-downloader#103]
Is there any way I can use a proxy?

**Comment by tusharmath** [comment]
All the params are by default passed to the [request](https://www.npmjs.com/package/request#proxies) module while making the HTTP requests.

Could you try —
```js
createDownload({path, url, proxy: 'localhost:9000'})
```

**Comment by ohenepee** [comment]
Thanks!

**Comment by agarwalkartik** [comment]
> All the params are by default passed to the [request](https://www.npmjs.com/package/request#proxies) module while making the HTTP requests.
> 
> Could you try —
> 
> ```js
> createDownload({path, url, proxy: 'localhost:9000'})
> ```

Hey, is the method ``` createDownload() ``` now deprecated ? cannot find it in the docs. I need to use socks 5 proxy connection to download files
