### ISSUE TITLE
basic auth in options?

### ISSUE THREAD

**Issue by pantchox** [tusharmath/Multi-threaded-downloader#165]
how do you implement this in mtd?

thanks.

**Comment by tusharmath** [comment]
You can pass the auth params to the `request()` function — https://github.com/tusharmath/Multi-threaded-downloader#HTTP.request

**Comment by pantchox** [comment]
how?
the master branch does README not have clear examples on how to use MTD, which makes it very unattractive to use.

**Comment by tusharmath** [comment]
Sorry if the README isn't clear. I'd be happy to merge a PR if you think it can be made better.

Internally mtd use the npm's `request` module for making HTTP requests. So to create a new HTTP request you could do something like — 

```js
const response$ = HTTP.request({
  url : 'a.b.c',
  auth: {
    'user': 'username',
    'pass': 'password',
    'sendImmediately': false
  }
}) 
```

**Comment by pantchox** [comment]
Thanks.
I mean that in the other branches (which i have no idea which one is the most update one) the README is more clear and with examples of the options.

Thanks for MTD its really good!

**Comment by tusharmath** [comment]
@pantchox `master` is the most updated branch right now. I'd be more than happy to fix the documentation.

**Comment by pantchox** [comment]
A simple basic usage example such as requiring the module and instantiating the class with the download options and events (start, pause, resume, finish) would make it more clear, its nice that the library looks very maintained and all the objects are being described what they do and all BUT there is NON of any examples of simple usage, digging in other branches/tags shows examples but how do i know they are aligned with this latest release.
I am not trying to be annoying or having something served on a silver plate i am just saying that simple users like me need to have a concrete USAGE example. 
Thanks!
