### ISSUE TITLE
Add download stop action

### ISSUE THREAD

**Issue by tusharmath** [tusharmath/Multi-threaded-downloader#20]
The lib should have an option of stopping the download

**Comment by tusharmath** [comment]
Since `response$` is now available its possible to destroy HTTP requests.

**Comment by ohenepee** [comment]
How exactly is this supposed to be used?

    Expose response$ externally for manually destroying

**Comment by tusharmath** [comment]
@ohenepee Here is an example for version 2.0 —

```js
const [{response$, meta$}] = DownloadFromMTDFile('/hello.txt.mtd')
response$.subscribe(response => {
  setTimeout(() => response.destroy(), 1000) // stops the download after 1 second
})
```

PS: Install version 2.0 — `npm i mt-downloader@next`

**Comment by ohenepee** [comment]
You're just awesome!
