### ISSUE TITLE
Not able to download files that require cookies

### ISSUE THREAD

**Issue by tusharmath** [tusharmath/Multi-threaded-downloader#23]
Some requests require cookies. Something needs to be done so that cookies also be supplied with the request. This should also incorporate downloading files that need authentication.

**Comment by krzysztofantczak** [comment]
+1

**Comment by tusharmath** [comment]
Are you using the cli wrapper or just the lib?

**Comment by starak** [comment]
+1

**Comment by krzysztofantczak** [comment]
@tusharmath i was planning to use a lib, but no cookies == no use for me.

**Comment by tusharmath** [comment]
alright wait
