### ISSUE TITLE
Stop a download

### ISSUE THREAD

**Issue by leeroybrun** [tusharmath/Multi-threaded-downloader#33]
Hi,

Thanks for your module, it's very usefull and working great !

Is there an easy way to stop (cancel) a download ?

**Comment by tusharmath** [comment]
There is no easy way to do this as of now. The only way you can do it is as follows - 


```js

var mtd = require('mt-downloader');

var url = 'https://upload.wikimedia.org/wikipedia/commons/4/47/Gadget_the_pug_expressive_eyes.jpg';
var file = './Gadget_the_pug_expressive_eyes.jpg';

var downloader = new mtd(file, url, {
    onStart: function (threads) {
        threads.each(function(i){
            i.destroy();
        });
    }
});

downloader.start();
```

I hope this helps. I would be glad to merge a pull request which would make it easier.

**Comment by leeroybrun** [comment]
It seems quite easy, just what I needed.
Thanks !

**Comment by rtmcached** [comment]
Is it safe to just destroy the threads? I implemented your proposal and sometimes I get a corrupted mtd file, which cannot be resumed.

**Comment by skarppion101** [comment]
I think you should send a destroy event to the thread



Sent from Mail.Ru app for iOS


Thursday 14 January 2016 18:24 +0300 from notifications@github.com  <notifications@github.com>:

**Comment by rtmcached** [comment]
Yes, that's what I do. But my question is if it is safe do to so? Because sometimes I get corrupted mtd file, which can not be resumed...
