### ISSUE TITLE
Download on Windows can't completed after resume 

### ISSUE THREAD

**Issue by nishantcop** [tusharmath/Multi-threaded-downloader#36]
After resume downloads progress it shows 100% but present with an error :- 
"{ [Error: EPERM, ftruncate] errno: -4048, code: 'EPERM' }"

Also, *.mtd file size seems just doubled. 

I am using node version 0.12.2
and mtd version 0.0.9
OS: windows 8.1

**Comment by tusharmath** [comment]
@nishantcop This is a problem with nodejs  on windows. Can you also try the same with io.js?

**Comment by martingg88** [comment]
ya.. i do have this issue. any idea how to solve it?

**Comment by tusharmath** [comment]
Issue has been fixed in the latest (1.0.0) version
