### ISSUE TITLE
Explicit Stop, Pause, Resume and Destroy functionality

### ISSUE THREAD

**Issue by nishantcop** [tusharmath/Multi-threaded-downloader#38]
STOP: Current download will be stopped and cleared
PAUSE: Should pause the current going download or downloadTask that is passed as  argument. 
RESUME: Should be able to resume specific download task by just providing ID or URL. 
DESTROY: handle cleaning up all threaded nicely if it's not done.

**Comment by tusharmath** [comment]
Duplicate of #20
