### ISSUE TITLE
Option to set max download speed

### ISSUE THREAD

**Issue by irvingswiftj** [tusharmath/Multi-threaded-downloader#46]
Hi,

It would be very nice if there was an option that would allow us to limit the speed of a download.

**Comment by tusharmath** [comment]
Its not possible, because the server would keep pushing the data and if not used it would keep on filling the buffer untill the overflows.

**Comment by irvingswiftj** [comment]
Ah, that is a shame. As it is a requirement from my client, I will have to use another module.
