### ISSUE TITLE
corrupt download, using electron

### ISSUE THREAD

**Issue by Riuujin** [tusharmath/Multi-threaded-downloader#47]
I am trying to use this module in electron to download a file.
However I keep getting the following error:
>err = Error: UNKNOWN: unknown error, write at Error (native) {errno: -4094, code: "UNKNOWN", >syscall: "write", message: "UNKNOWN: unknown error

within the "mt-downloader\lib\core\DownloadWriterAsyncTask.js" write method.

Any idea what this might be or is it just that i am trying to use it with electron?

**Comment by tusharmath** [comment]
Did you check these links —
Stackoverflow : http://stackoverflow.com/questions/29414803/read-writing-files-in-node-with-fs-via-unc-path

Gihub: https://github.com/nodejs/node-v0.x-archive/issues/8821
