### ISSUE TITLE
File meta truncating sometimes not working.

### ISSUE THREAD

**Issue by rtmcached** [tusharmath/Multi-threaded-downloader#50]
> This file contains some meta information related to the download and is a little bigger (around 10kb) than the original download size.

Sometimes the downloaded file is 10kb bigger than the file on the server, so I suspect that the meta is not truncated.

**Comment by tusharmath** [comment]
Is there an exception being thrown? Can you provide more details?

Try doing —

```
curl -i -X HEAD <the url that has the file>
```

**Comment by rtmcached** [comment]
Nope, no exception, just the file not being truncated.

    curl -i -X HEAD <the url that has the file>
shows the same Content-Length as ls -l file size


I modified TruncateAsyncTask.js to
```
var _execute = function(callback) {

  this.callback = callback;
  var self = this;
  fs.ftruncate(this.fd, this.fileSize, function (err) {
    if (err) console.log(err);

    var truncatedFileSize = fs.fstatSync(self.fd).size;
    console.log('truncating', truncatedFileSize === self.fileSize ? 'success' : 'failed', truncatedFileSize, self.fileSize);

    return self.callback(err);
  });
  //this.callback();
};
```
and sometimes I get truncating failed (not all the time), but no err.

Probably ftruncate silences or do not see the err...

**Comment by tusharmath** [comment]
Take a look at #43. I will close this.
