### ISSUE TITLE
Stopping a download

### ISSUE THREAD

**Issue by rtmcached** [tusharmath/Multi-threaded-downloader#51]
In issue #33 in order to stop a download you propose
```
var downloader = new mtd(file, url, {
    onStart: function (data) {
        data.threads.each(function(i){
            i.destroy();
        });
    }
});
```
Is it safe to just destroy the threads? I implemented your proposal and sometimes I get a corrupted mtd file, which cannot be resumed.

**Comment by tusharmath** [comment]
@rtmcached It shouldn't be a problem to destroy the threads at all. Killing a http request is a very legitimate operation. This is also done, automatically when a connection remains idle for more than 5 seconds.

**Comment by rtmcached** [comment]
I am on Lubuntu 14.04 x64 and it seems after implementing #43, the corrupted mtd files no longer appears
