### ISSUE TITLE
can't run the example

### ISSUE THREAD

**Issue by continuata** [tusharmath/Multi-threaded-downloader#63]
when I execute

```js
  var createDownload = require('mt-downloader').createDownload
  var url = 'http://upload.wikimedia.org/wikipedia/commons/4/47/Gadget_the_pug_expressive_eyes.jpg'
  var path = './Gadget_the_pug_expressive_eyes.jpg'
  const downloader = createDownload({path, url})
  downloader.stats.subscribe(x => console.log(x))
  downloader.start()
```
It creates a file called `Gadget_the_pug_expressive_eyes.jpg.mtd` of 0 bytes and doesn't download anything.
It gives the correct INIT event output

```
{ event: 'INIT',
  message:
   { path: '/Users/stukennedy/electron-quick-start/Gadget_the_pug_expressive_eyes.jpg',
     url: 'http://upload.wikimedia.org/wikipedia/commons/4/47/Gadget_the_pug_expressive_eyes.jpg',
     range: 3,
     mtdPath: '/Users/stukennedy/electron-quick-start/Gadget_the_pug_expressive_eyes.jpg.mtd' } }
```

but then does nothing. What am I missing?

**Comment by tusharmath** [comment]
can you try `  downloader.start().toPromise`?

**Comment by continuata** [comment]
I did try that, same issue.

In fact I installed mtb and that did the same thing

**Comment by tusharmath** [comment]
Take a look at the logs here — https://tonicdev.com/tusharmath/56e28b9f1040981100270479

**Comment by continuata** [comment]
I don't doubt it works generally, but I just can't get it to download on my machine.
I upgraded node to the latest version, but same problem.
I'm on a Mac and wondered if there's some Gatekeeper setting blocking it.

(BTW love the FRP stuff in your code, very rare to see nicely thought through FRP)

**Comment by continuata** [comment]
I've tried it on a different Macbook and it works great ... but need to figure out why it's not working on mine. Any ideas what I can try, to figure out what's stopping it?

**Comment by continuata** [comment]
seems I was being stupid, looks like I didn't save the version with `.toPromise()` on it before I tested.
Without the promise, the node thread just returns and exits the app, which was why it wasn't downloading  ... apologies

**Comment by tusharmath** [comment]
LOL. No probs :)
