### ISSUE TITLE
trying to use mt-donwloader in Electron with ReactJS 

### ISSUE THREAD

**Issue by continuata** [tusharmath/Multi-threaded-downloader#64]
I'm desperately trying to get mt-downloader working with ReactJS in Electron

to start off with there was an issue with json-scheme having an issue with define, causing a crash which I was able to fix with
```
module: {
  noParse: /node_modules\/json-schema\/lib\/validate\.js/,
}
```
in `webpack.config`.

Now the app runs, but when I try to download, it initialises the download and crashes in an `createNodeObservable` method, because the function passed to it is undefined. This is when it is trying to call fsOpen.

Any ideas what I can do to fix this?
Here is the stack trace

<img width="723" alt="screen shot 2016-03-11 at 22 38 39" src="https://cloud.githubusercontent.com/assets/1593397/13717690/0916d0ec-e7db-11e5-9574-740b0bc6c3f2.png">

**Comment by tusharmath** [comment]
Enable source maps for easier debugging and stack trace. Its difficult to
say why you are getting this error. Also could you paste the code for
initiating the download?

On Sat, Mar 12, 2016, 4:16 AM Stu Kennedy <notifications@github.com> wrote:

> I'm desperately trying to get mt-downloader working with ReactJS in
> Electron
>
> to start off with there was an issue with json-scheme having an issue with
> define, causing a crash which I was able to fix with
>
> module: {
>   noParse: /node_modules\/json-schema\/lib\/validate\.js/,
> }
>
> in webpack.config.
>
> Now the app runs, but when I try to download, it initialises the download
> and crashes in an createNodeObservable method, because the function
> passed to it is undefined. This is when it is trying to call fsOpen.
>
> Any ideas what I can do to fix this?
> Here is the stack trace
>
> [image: screen shot 2016-03-11 at 22 38 39]
> <https://cloud.githubusercontent.com/assets/1593397/13717690/0916d0ec-e7db-11e5-9574-740b0bc6c3f2.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tusharmath/Multi-threaded-downloader/issues/64>.
>
-- 
Regards,
Tushar Mathur.
www.tusharm.com

**Comment by continuata** [comment]
OK so I've found out where it seems to be going wrong.

```js
	/**
	 * Created by tushar.mathur on 25/01/16.
	 */

	'use strict'
	const _ = __webpack_require__(368)

	module.exports = _.curry((ob, path, flag) => ob.fsOpen(path, flag))
```

`fsOpen` triggers the following callback 
```js
	/**
	 * Converts a Node.js callback style function to an observable sequence.  This must be in function (err, ...) format.
	 * @param {Function} fn The function to call
	 * @param {Mixed} [ctx] The context for the func parameter to be executed.  If not specified, defaults to undefined.
	 * @param {Function} [selector] A selector which takes the arguments from the callback minus the error to produce a single item to yield on next.
	 * @returns {Function} An async function which when applied, returns an observable sequence with the callback arguments as an array.
	 */
	Observable.fromNodeCallback = function (fn, ctx, selector) {
	  return function () {
	    typeof ctx === 'undefined' && (ctx = this); 
	    var len = arguments.length, args = new Array(len);
	    for(var i = 0; i < len; i++) { args[i] = arguments[i]; }
	    return createNodeObservable(fn, ctx, selector, args);
	  };
	};
```
But `fn` is undefined in the callback, so it must be something to do with `fsOpen`

Below is the code for my React Component trying to trigger the download
```jsx
import React from 'react'
import { createDownload } from 'mt-downloader'

let { Component } = React

export default class App extends Component {
  _download = () => {
    let url = 'http://upload.wikimedia.org/wikipedia/commons/4/47/Gadget_the_pug_expressive_eyes.jpg'
    let path = './Gadget_the_pug_expressive_eyes.jpg'
    const downloader = createDownload({path, url})
    downloader.stats.subscribe((x) => console.log(x))
    downloader.start().toPromise()
  }

  render () {
    return (
      <div>
        <h1>WELCOME!</h1>
        <button onClick={this._download}>DOWNLOAD</button>
      </div>
    )
  }
}
```

Screenshot below
<img width="1680" alt="screen shot 2016-03-12 at 09 45 21" src="https://cloud.githubusercontent.com/assets/1593397/13722260/383a3f74-e837-11e5-8b7e-67802965b223.png">

**Comment by tusharmath** [comment]
Is the code available on github? I could take a look if you'd like. I think webpack is not loading the `fs` module correctly. Take a look at this issue — https://github.com/chentsulin/electron-react-boilerplate/issues/1

**Comment by continuata** [comment]
Yeah that sounds plausible ... I've uploaded it here for you to take a look at

https://github.com/continuata/electronReact

**Comment by continuata** [comment]
I've figured it out ... followed this tutorial 
http://jlongster.com/Backend-Apps-with-Webpack--Part-I

It now downloads properly ... very happy indeed. :-)
