### ISSUE TITLE
downloading private AWS S3 URLs doesn't work

### ISSUE THREAD

**Issue by continuata** [tusharmath/Multi-threaded-downloader#66]
If I use an Amazon S3 Private (Signed) URL for downloading, the download progresses as though it is working, data is coming down the connection (I can see in my network inspector), but it isn't being saved to disk, when it's "completed" I end up with a file of 0 bytes.

It seems to have `null` in each of the threads, and also `totalBytes` is always null, when looking at the stats output/

<img width="908" alt="screen shot 2016-03-12 at 20 59 52" src="https://cloud.githubusercontent.com/assets/1593397/13725307/d4fb9908-e895-11e5-8614-1c953ec12af3.png">

A public file from S3 which doesn't have a signature works fine.

**Comment by continuata** [comment]
Looks like Amazon S3 won't let you see the whole HTTP header on a head request.

In `observables.js` you get the content-length from the header. I think that may be the issue
```js
module.exports = {
  requestBody,
  requestContentLength: x => requestBody(_.assign({}, x, {method: 'HEAD'}))
    .pluck('message', 'headers', 'content-length')
    .map(x => parseInt(x, 10)),
  fsOpen,
  fsWrite,
  fsWriteBuffer,
  fsWriteJSON,
  fsReadJSON,
  fsReadBuffer,
  fsTruncate,
  fsRename,
  fsStat,
  buffer
}
```

**Comment by continuata** [comment]
ok .. so playing around a bit, I reckon you can fix this by using a `GET` instead of a `HEAD` to get the content-length from the first response (similar to below)
```js
requestContentLength = x => requestBody(_.assign({}, x, {method: 'GET'}))
  .pluck('message', 'headers', 'content-length')
  .map(x => parseInt(x, 10))
```
but I can't figure out how to cancel the download once it's got the length, to allow the actual download to continue. Any ideas?

**Comment by tusharmath** [comment]
What are the HTTP headers that you get when requesting via `HEAD` vs `GET` ?

**Comment by continuata** [comment]
they are meant to be the same 

http://stackoverflow.com/questions/3854842/content-length-header-with-head-requests

but content length isnt always implemented in the HEAD response (as in AWS Signed links) ... so this is not a bug with mt-downloader, it's S3's fault; but we need a workaround that allows for this issue otherwise signed files can't be downloaded from S3 using mt-downloader. (that's practically all
I'll be using it for)

**Comment by tusharmath** [comment]
> but we need a workaround that allows for this issue 

AGREE.

Some changes might be required in the current implementation.

**Current Approach**
1. make HEAD request, parse content-length
2. divide content-length by thread-count and make multiple http requests.

**New Approach**
1. Directly make the HTTP request with the provided HTTP method.
2. Parse headers for content-length
    a. IF found: create new threads, auto destruct the first thread once the data downloaded reached the first byte of the second thread.
    b. IF Not Found: continue downloading with the current request. If its a resume, only set the start byte and not the end byte for that one thread.

So this will also cover chunked downloads.

**Comment by continuata** [comment]
wouldn't it be easier to just do
1. make GET request, parse content-length
2. cancel GET request before downloading any data
3. divide content-length by thread-count ... etc

**Comment by tusharmath** [comment]
Why cancel? It would be inefficient to destroy an already created connection and then create another.

**Comment by tusharmath** [comment]
Just to solve your problem. Would you mind pasting the Headers of both the HEAD and GET responses?

**Comment by continuata** [comment]
Yeah good point ... I was just being lazy ;-)

Here are the headers. There's a 403 (Forbidden) error on the HEAD request.

<img width="740" alt="screen shot 2016-03-13 at 20 10 11" src="https://cloud.githubusercontent.com/assets/1593397/13731020/b8b0332c-e957-11e5-90ce-f626a99d5444.png">
<img width="737" alt="screen shot 2016-03-13 at 20 09 51" src="https://cloud.githubusercontent.com/assets/1593397/13731021/ba8671c0-e957-11e5-977d-35503fc65386.png">

**Comment by tusharmath** [comment]
To solve your problem temporarily you can set the threadCount to 1 if content-length is not available. The permanent solution would be to not make HEAD requests ever instead dynamically decide after making the get request.
