### ISSUE TITLE
resuming download with expired URL

### ISSUE THREAD

**Issue by continuata** [tusharmath/Multi-threaded-downloader#83]
some URLs have an expiry (e.g. AWS S3 signed links).
When you resume download it will resume using the original URL set in the `mtd` 
(which may have expired)

Is it possible to update the URL before resuming?

**Comment by tusharmath** [comment]
@continuata Not possible as of now, but sounds like a really important feature.

**Comment by tusharmath** [comment]
I think it's time to decompose this monolithic module into smaller chunks. That way it would be much easier for someone to just select different components and build their own downloader.

**Comment by continuata** [comment]
any ideas how I would get this working?
Trying to figure out this process.

**Comment by tusharmath** [comment]
I think for now you can pass `this.options` here — https://github.com/tusharmath/Multi-threaded-downloader/blob/master/src%2Fmtd.js#L37

And merge it with `loadedMETA`.

**Comment by continuata** [comment]
so you'd do something like

```
  download () {
    const fd = this.fd('r+')
    const options = this.options
    const ob = this.ob
    return downloadMTD(ob, fd, options)
      .tap(this.toStat('DATA'))
      .last()
      .flatMap((x) => ob.fsTruncate(options.mtdPath, x.totalBytes))
      .tap(this.toStat('TRUNCATE'))
      .flatMap(() => ob.fsRename(options.mtdPath, options.path))
      .tap(this.toStat('RENAME'))
      .tapOnCompleted((x) => this.stats.onCompleted())
  }
```

and then in `downloadMTD.js` do:
```
module.exports = (ob, fd, options) => {
  const offsets = create(Immutable.List([]))
  const loadedMETA = metaLoad(fd)
    .merge(options)
    .tap((x) => offsets.set((i) => i.merge(x.offsets)))
  const loadedContent = contentLoad(ob, loadedMETA)
  const savedContent = bufferSave(ob, fd, loadedContent)
    .tap((x) => offsets.set((i) => i.set(x.index, x.offset)))
  const currentMETA = metaUpdate(loadedMETA, savedContent, offsets.stream)
  return metaSave(ob, fd, currentMETA)
}
```
?

Also we'd need to take out the `.skipWhile((x) => x.url)` in resumeDownload
Would that work?

(still a bit confused how this all hangs together ... e.g. where does it choose to use resumeDownload or newDownload?)

**Comment by tusharmath** [comment]
I think something like this should be better —

```js
metaLoad(fd).map(meta => _.assign({}, options, meta))
```
`resumeDownload` is only used by cli, so that needn't be touched.

**Comment by continuata** [comment]
hmmm ... it just starts the download from the beginning each time, it doesn't resume.
Let me create a PR for this so you can see what I'm doing

**Comment by tusharmath** [comment]
It doesn't make sense to handle all the cases in this module. It's better to expose some additional internal APIs to write your own custom logic or even better, create plugins on top of it.

**Comment by tusharmath** [comment]
@continuata Had to re-write the module for this feature :) Finally it should be available on `next` tag in a few minutes.
