### ISSUE TITLE
Not able to download files from CDN

### ISSUE THREAD

**Issue by pavanbuzz** [tusharmath/Multi-threaded-downloader#89]
Hi,

It is having some issue while trying to download a CDN url, "http://dt67.energycdn.com/zip/2nxVlNhjAUiZ3Wj76L1z4g/1464673445/3460716/27f7c553f3e79ce9b7f5a138d21f28bc195ee842".

It just creates "INIT" event, and stops.

**Comment by continuata** [comment]
in your packages.json what version of mt-downloader does it say you're using?
I think npm may be one version behind the github

**Comment by pavanbuzz** [comment]
Current version is 1.4.1

**Comment by continuata** [comment]
it should be 1.4.2 ... try forcing the update
```
npm install mt-downloader@1.4.2
```

**Comment by continuata** [comment]
it should download the file, but it's likely that the stats reporting will still be wrong (totalBytes and threads will likely be null) ... currently working on this bug in issue #88

**Comment by tusharmath** [comment]
@pavanbuzz @continuata The latest version is `1.5.1`
```
npm i mt-downloader@latest
```

**Comment by continuata** [comment]
oh ok, I'm a bit behind then ;-) ... maybe it's just the badge then on the github page now.

**Comment by tusharmath** [comment]
@continuata That just represents the stable version.

**Comment by pavanbuzz** [comment]
Am using the latest version which is 1.5.1. Am unable to download it still. Are you guys able to download that link using mt-downloader?

**Comment by tusharmath** [comment]
@pavanbuzz Please install via `npm i mt-downloader@next` and then try.

**Comment by tusharmath** [comment]
@pavanbuzz Yes I was able to download your link.

**Comment by pavanbuzz** [comment]
@tusharmath I tried to print the events and the following was only obtained,

```
{ event: 'INIT',
  message:
   { path: 'Preacher.S01E01.HDTV.x264-FLEET.mkv',
     url: 'https://dt67.energycdn.com/torrentdl/qipDOkCLIaNuZBM4uIaLHQ/1464674288/3460716/27f7c553f3e79ce9b7f5a138d21f28bc195ee842/Preacher.S01E01.HDTV.x264-FLEET%5Brarbg%5D/Preacher.S01E01.HDTV.x264-FLEET.mkv',
     range: 3,
     mtdPath: 'Preacher.S01E01.HDTV.x264-FLEET.mkv.mtd' } }
```
The following is the piece of code that I have,

`var createDownload = require('mt-downloader').createDownload;
var url = 'https://upload.wikimedia.org/wikipedia/commons/4/47/Gadget_the_pug_expressive_eyes.jpg';
url='https://dt67.energycdn.com/torrentdl/qipDOkCLIaNuZBM4uIaLHQ/1464674288/3460716/27f7c553f3e79ce9b7f5a138d21f28bc195ee842/Preacher.S01E01.HDTV.x264-FLEET%5Brarbg%5D/Preacher.S01E01.HDTV.x264-FLEET.mkv';
var path = 'Preacher.S01E01.HDTV.x264-FLEET.mkv'
var downloader = createDownload({path, url});
downloader.stats.subscribe((x) => complete(x));
downloader.start().toPromise();
console.log('Waiting for download to finish');`

**Comment by tusharmath** [comment]
@pavanbuzz take a look at this code here — 

**Current**
```js
downloader.start().toPromise();
```
This is returning a promise and you need to add an error handler such as —

```js
downloader.start().toPromise(x => console.log('SUCCESS'), err => console.error('ERROR', err));
```

or use `done()` as follows 

```js
downloader.start().toPromise().done()
```

**Comment by pavanbuzz** [comment]
@tusharmath  It works.. thanks a lot mate.. However, what other options can we pass to createDownload() ?

**Comment by tusharmath** [comment]
Apart from the ones that are documented in the README, you can pass anything that the [request](https://www.npmjs.com/package/request) module can accept.

**Comment by pavanbuzz** [comment]
Thanks a lot for the clarification.
