### ISSUE TITLE
bin/mtd.js won't run

### ISSUE THREAD

**Issue by continuata** [tusharmath/Multi-threaded-downloader#97]
I'm getting an error using ES6 style imports in the mtd.js implementation.
```
import Rx from 'rx'
^^^^^^
SyntaxError: Unexpected token import
```
I've got Node version v6.2.1 installed.
Any ideas?

**Comment by tusharmath** [comment]
@continuata Issue was fixed here — https://github.com/tusharmath/Multi-threaded-downloader/commit/84fceee6

Please use version `1.5.2`
